const tenantConfigs = {
   
    portfolio: {
      EMAIL_SERVICE: process.env.PORTFOLIO_EMAIL_SERVICE,
      EMAIL_USER: process.env.PORTFOLIO_EMAIL_USER,
      EMAIL_PASS: process.env.PORTFOLIO_EMAIL_PASS,
      OWNER_EMAIL: process.env.PORTFOLIO_OWNER_EMAIL,
    
    MONGO_URI: process.env.PORTFOLIO_MONGO_URI,
    FRONTEND_URL_PRODUCTION: process.env.PORTFOLIO_FRONTEND_URL_PRODUCTION,
    FRONTEND_URL_DEVELOPMENT: process.env.PORTFOLIO_FRONTEND_URL_DEVELOPMENT,

    },


    anahuac: {
      MONGO_URI: process.env.ANAHUAC_MONGO_URI,
      FRONTEND_URL_PRODUCTION: process.env.ANAHUAC_FRONTEND_URL_PRODUCTION,
    FRONTEND_URL_DEVELOPMENT: process.env.ANAHUAC_FRONTEND_URL_DEVELOPMENT,
JWT_SECRET: process.env.ANAHUAC_JWT_SECRET,
EMAIL_SERVICE: process.env.ANAHUAC_EMAIL_SERVICE,
      EMAIL_USER: process.env.ANAHUAC_EMAIL_USER,
      EMAIL_PASS: process.env.ANAHUAC_EMAIL_PASS,
      OWNER_EMAIL: process.env.ANAHUAC_OWNER_EMAIL,
    CLOUDINARY_CLOUD_NAME:process.env.ANAHUAC_CLOUDINARY_CLOUD_NAME,
 CLOUDINARY_API_KEY:process.env.ANAHUAC_CLOUDINARY_API_KEY,
 CLOUDINARY_API_SECRET:process.env.ANAHUAC_CLOUDINARY_API_SECRET,
OPENAI_API_KEY:process.env.ANAHUAC_OPENAI_API_KEY,
    },

     rricura: {
      EMAIL_SERVICE: process.env.RRICURA_EMAIL_SERVICE,
      EMAIL_USER: process.env.RRICURA_EMAIL_USER,
      EMAIL_PASS: process.env.RRICURA_EMAIL_PASS,
      OWNER_EMAIL: process.env.RRICURA_OWNER_EMAIL,
      STRIPE_SECRET_KEY: process.env.RRICURA_STRIPE_KEY,
      MONGO_URI: process.env.RRICURA_MONGO_URI,
       FRONTEND_URL_PRODUCTION: process.env.RRICURA_FRONTEND_URL_PRODUCTION,
    FRONTEND_URL_DEVELOPMENT: process.env.RRICURA_FRONTEND_URL_DEVELOPMENT,
    ORS_API_KEY: process.env.RRICURA_ORS_API_KEY,
    BUSINESS_ADDRESS: process.env.RRICURA_BUSINESS_ADDRESS,

    },

  dashboard: {
    FRONTEND_URL_PRODUCTION: process.env.DASHBOARD_FRONTEND_URL_PRODUCTION,
  FRONTEND_URL_DEVELOPMENT: process.env.DASHBOARD_FRONTEND_URL_DEVELOPMENT,
   MONGO_URI: process.env.DASHBOARD_MONGO_URI,
  JWT_SECRET: process.env.DASHBOARD_JWT_SECRET,
    },

  

 uv: {
    FRONTEND_URL_PRODUCTION: process.env.UV_FRONTEND_URL_PRODUCTION,
  FRONTEND_URL_DEVELOPMENT: process.env.UV_FRONTEND_URL_DEVELOPMENT,
 

     },

     tamalepos: {
    FRONTEND_URL_PRODUCTION: process.env.TAMALE_POS_FRONTEND_URL_PRODUCTION,
  FRONTEND_URL_DEVELOPMENT: process.env.TAMALE_POS_FRONTEND_URL_DEVELOPMENT,
  MONGO_URI: "", // stays empty
 
    },


  };
  
  module.exports = tenantConfigs;
  